services:

    generator.structure.application:
        class: AngryBytes\GeneratorBundle\Structure\Application
        arguments:
            - @=service('project_layout').getRoot()
        calls:
            - [setTwig, [@project.twig.environment]]

    # Generate application command
    generator.project.console.command.application:
        class: AngryBytes\GeneratorBundle\Command\ApplicationCommand
        calls:
            - [setStructure, [@generator.structure.application]]
            - [setDirectoryLayout, [@project_layout]]
            - [setApplications, [@applications]]
        tags:
            - name: project.console.command

    # FileGen Helper
    generator.project.console.helper.fileGen:
        class: Naneau\FileGen\Console\Helper\ParameterHelper
        tags:
            - name: project.console.application.helper
              alias: filegenParameters
